//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetBankingUserRequest
    {
        public int Id { get; set; }
        public string IdCard { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string CellPhone { get; set; }
        public string WorkTel { get; set; }
        public string Address { get; set; }
        public string WorkAddress { get; set; }
        public string PersonalEmail { get; set; }
        public string WorkEmail { get; set; }
        public System.DateTime RequestDate { get; set; }
        public bool RequestStatus { get; set; }
        public string StatusComment { get; set; }
        public Nullable<int> EmployeeAuthorizationID { get; set; }
        public Nullable<System.DateTime> DateAuthorization { get; set; }
    }
}
