//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccounts
    {
        public int Id { get; set; }
        public string IdCard { get; set; }
        public string Accountnumber { get; set; }
        public string AccountType { get; set; }
        public string MoneyType { get; set; }
        public decimal Initial_Balance { get; set; }
        public decimal Actual_Balance { get; set; }
        public decimal Disponible_Balance { get; set; }
        public decimal TotalTransition { get; set; }
        public System.DateTime LastCut { get; set; }
    }
}
